services:
  backend:
    build: ./backend
    env_file:
      - vars.env

  frontend:
    build: ./frontend
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build

  db:
    image: postgres
    restart: always
    env_file:
      - vars.env

  nginx:
    image: nginx:1.21.3
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  web-client-build:
