services:
  backend:
    build: ./backend
    env_file:
      - vars.env

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

  db:
    image: postgres
    restart: always
    env_file:
      - vars.env

  nginx:
    image: nginx:1.21.3
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/src:/web-client-build
      - ./logs:/var/log/nginx
volumes:
  postgres:
  web-frontend-build:
