services:
  backend:
    build: ./backend
    ports:
      - 4000:4000
    env_file:
      - vars.env
    volumes:
      - ./backend/src:/app/src

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

  admin:
    build: ./admin
    ports:
      - 3001:3000
    volumes:
      - ./admin/src:/app/src

  db:
    image: postgres
    restart: always
    env_file:
      - vars.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
