POST http://localhost:5000/api/skill
Content-Type: application/json

{
    "name": "JS"
}

###
GET http://localhost:5000/api/skill

###
DELETE http://localhost:5000/api/skill/1

###
PUT http://localhost:5000/api/skill/2
Content-Type: application/json

{
    "name": "Ruby"
}